name: CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:


jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4

      - run: uv run ./nocomps.py

      - uses: stefanzweifel/git-auto-commit-action@v5
