name: CI

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:


jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - run: uv run ./nocomps.py -o "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v5
